### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by NehaKushwah993** [theaayushsharma/Animated-Gif#1]
The gif is not getting played, for this original project. I didn't change any thing.

**Comment by PrashantMangale** [comment]
> The gif is not getting played, for this original project. I didn't change any thing.

Yes. Even in my case too it's not working.

**Comment by NehaSukhlecha** [comment]
> The gif is not getting played, for this original project. I didn't change any thing.



> > The gif is not getting played, for this original project. I didn't change any thing.
> 
> Yes. Even in my case too it's not working.

Please check updated the code
